# This conda recipe is for use with the git repo (hence the local url).
# For a simple conda install (non bleeding-edge), see the conda-forge recipe at
# https://github.com/conda-forge/jupyter_highlight_selected_word-feedstock

{% set name = 'jupyter_highlight_selected_word' %}

package:
  name: {{ name }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - jupyter_contrib_core >=0.3
    - notebook >=4.0

test:
  imports:
    - jupyter_highlight_selected_word

about:
  summary: |
    Jupyter notebook extension that enables highlighting of all instances of
    the currently-selected or cursor-adjecent word in either the current cell's
    editor, or in the whole notebook.
    Based on the  CodeMirror addon
    https://codemirror.net/demo/matchhighlighter.html
    extended to work across multiple editors.
  home: https://github.com/jcb91/jupyter_highlight_selected_word
  license_file: LICENSE.txt
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jcb91
